import type { Metadata } from "next";

import "./globals.css";

import ToastProvider from "@/components/providers/toast-provider";
import QuestionMarkPopup from "@/components/QuestionMarkPopup";



export const metadata: Metadata = {
  title: "Book R",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#F0F2FF]`}>
        <ToastProvider />
        {children}
        <QuestionMarkPopup />
      </body>
    </html>
  );
}
